import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Laura | Web Developer</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.about}>

        <div className={styles.profile}>
          <Image src="/me.png" width={400} height={400} />
        </div>
        <div className={styles.bio}>
          <h1 className="heading">Welcome!</h1>
          <p>I remember designing my very first custom MySpace layout and thinking "Whoa, that is so <i>COOL</i>!"

          I grew up firmly believing that I would be an equine veterinarian, or a dancer, or an actor, or an event planner, or a TEFL teacher in South Korea.
          <br/><br/>
          Basically, I've been all over the place in terms of passions and career interests.
          <br/><br/>
          I stumbled upon some online coding tutorials and suddenly I was that 12 year old girl, sitting in front of her computer creating her own layout again. Coding has ignited a drive in me that I thought I had lost. It allows me to be as creative as I want, I get to problem solve on a daily basis, and the work never gets boring.
          <br/><br/>
          I love how there's not really a wrong or right answer in web development, just different paths developers take to get to a solution. The collaborative aspect of this field is something that I really thrive on. I'm excited to learn from others and pass on knowledge and advice where I can!</p>
        </div>
      </div>
      <div className={styles.skills}>
        <h1 className="heading">My Skills</h1>
        <div className={styles.skillimgs}>
          <Image src="/illustrations/big3_lt.svg" width={200} height={200} />
          <Image src="/illustrations/nextjs_lt.svg" width={200} height={200} />
          <Image src="/illustrations/react_lt.svg" width={200} height={200} />
        </div>
      </div>
    </div>
  )
}
